"""empty message

Revision ID: 707f73a14c1c
Revises: e6906da40d7f
Create Date: 2024-05-21 18:48:46.543782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '707f73a14c1c'
down_revision = 'e6906da40d7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('confirmed_on', sa.DateTime(), nullable=True),
    sa.Column('verification_token', sa.String(), nullable=True),
    sa.Column('token_expiration', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('verification_token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
